/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package premierintgraph_berger;

/**
 *
 * @author berge
 */
public class fenêtrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form fenêtrePrincipale
     */
    public fenêtrePrincipale() {
        initComponents();
        
        System.out.println("fenêtre créée");
        msgBienvenue.setText("Hello !");
        labelResultat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgBienvenue = new javax.swing.JLabel();
        msgAurevoir = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        msgPrenom = new javax.swing.JLabel();
        zoneMot = new javax.swing.JTextField();
        labelResultat = new javax.swing.JLabel();
        msgSalaire = new javax.swing.JLabel();
        zoneSalaire = new javax.swing.JTextField();
        boutonSalaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        msgBienvenue.setText("Bonjour !");

        msgAurevoir.setText("Au revoir !");

        boutonValider.setBackground(new java.awt.Color(204, 0, 204));
        boutonValider.setForeground(new java.awt.Color(255, 255, 255));
        boutonValider.setText("Cliquez ici !");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        msgPrenom.setText("Entrez votre prénom :");

        zoneMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneMotActionPerformed(evt);
            }
        });

        labelResultat.setText("Resultat");

        msgSalaire.setText("Entrez votre salaire :");

        zoneSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneSalaireActionPerformed(evt);
            }
        });

        boutonSalaire.setText("Promotion !!");
        boutonSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(msgBienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonValider)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msgSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(boutonSalaire))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msgPrenom)
                                .addGap(18, 18, 18)
                                .addComponent(zoneMot, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgAurevoir)
                            .addComponent(zoneSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(msgBienvenue)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgPrenom)
                    .addComponent(zoneMot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelResultat)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgSalaire)
                    .addComponent(zoneSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonSalaire))
                .addGap(36, 36, 36)
                .addComponent(msgAurevoir)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        msgAurevoir.setText("Goodbye !");
        labelResultat.setVisible(true);
        String a = zoneMot.getText();
        labelResultat.setText("Comment ça va " + a + " ?");
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void zoneMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneMotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneMotActionPerformed

    private void boutonSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSalaireActionPerformed
        String salaire = zoneSalaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier += 100;
        zoneSalaire.setText(salaire_entier+"");
    }//GEN-LAST:event_boutonSalaireActionPerformed

    private void zoneSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new fenêtrePrincipale().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonSalaire;
    private javax.swing.JButton boutonValider;
    private javax.swing.JLabel labelResultat;
    private javax.swing.JLabel msgAurevoir;
    private javax.swing.JLabel msgBienvenue;
    private javax.swing.JLabel msgPrenom;
    private javax.swing.JLabel msgSalaire;
    private javax.swing.JTextField zoneMot;
    private javax.swing.JTextField zoneSalaire;
    // End of variables declaration//GEN-END:variables
}
